# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('invites', '0002_auto_20180101_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioneventinvite',
            old_name='invitee',
            new_name='sub',
        ),
        migrations.RemoveField(
            model_name='sessioneventinvite',
            name='event',
        ),
        migrations.AddField(
            model_name='sessioneventinvite',
            name='captain',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUser'),
            preserve_default=False,
        ),
    ]
