# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('invites', '0003_auto_20180102_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioneventinvite',
            name='captain',
        ),
        migrations.AddField(
            model_name='sessioneventinvite',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
            preserve_default=False,
        ),
    ]
