# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('substitutes', '0001_initial'),
        ('invites', '0004_auto_20180105_0213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessioneventinvite',
            unique_together=set([('sub', 'team')]),
        ),
    ]
