# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuserplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonuserplayer_set', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='captain',
            unique_together=set([('user', 'division')]),
        ),
    ]
