# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20180122_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captainrequest_set', to='divisions.Division')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captainrequest_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='captainrequest',
            unique_together=set([('user', 'division')]),
        ),
    ]
