# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180106_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='team_set', to='accounts.CustomUser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='accounts.CustomUser'),
        ),
    ]
