# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0006_remove_division_teams'),
        ('teams', '0003_auto_20180120_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='divisions_set', to='divisions.Division'),
            preserve_default=False,
        ),
    ]
