# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
    ]
