# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublist',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=120),
            preserve_default=False,
        ),
    ]
