# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0003_sublist_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
