# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0004_auto_20170807_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='session',
        ),
    ]
