# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:43
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170807_0343'),
        ('sublist', '0005_remove_sublist_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublist',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sublist',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='session'),
        ),
    ]
