# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0006_auto_20170807_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='session',
        ),
    ]
