# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170807_0448'),
        ('sublist', '0007_remove_sublist_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sublist',
            name='slug',
        ),
        migrations.AddField(
            model_name='sublist',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
            preserve_default=False,
        ),
    ]
