# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 02:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='slug',
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name'),
        ),
    ]
