# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='represented_divisions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
