# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_auto_20180119_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
