# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('divisions', '0003_auto_20180119_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivRepRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUser')),
            ],
        ),
    ]
