# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0004_divreprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divreprequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divreprequest', to='accounts.CustomUser'),
        ),
    ]
