# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0005_auto_20180120_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='teams',
        ),
    ]
