# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_has_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
