# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 02:05
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=accounts.models.thumbnail_path)),
                ('activation_key', models.CharField(default=accounts.models.generate_key, max_length=6)),
                ('key_expires', models.DateTimeField(default=accounts.models.generate_expiration)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'permissions': (('can_permit_add_team', 'Can permit other users to have add_team permissions (i.e., is Division Rep)'),),
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
