# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 17:03
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=accounts.models.generate_key, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=accounts.models.generate_expiration),
        ),
    ]
