# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180106_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
