# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180113_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_permit_add_team', 'Can permit other users to have add_team permissions (i.e., is Division Rep)'),)},
        ),
    ]
