# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='sub date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('other_players', models.ManyToManyField(blank=True, to='main.Player')),
                ('team_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='main.Player')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='division_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_representative', to='main.Player'),
        ),
        migrations.AddField(
            model_name='division',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='divisions_subs', to='main.Sub'),
        ),
        migrations.AddField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='divisions_teams', to='main.Team'),
        ),
    ]
