# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.Team'),
        ),
    ]
