# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170725_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
