# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170820_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, to='main.Team'),
        ),
    ]
