# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170820_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name'),
        ),
    ]
