# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170725_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='subs',
        ),
        migrations.AddField(
            model_name='session',
            name='subs',
            field=models.ManyToManyField(blank=True, to='main.Sub'),
        ),
    ]
