# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_team_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('slug', 'team_captain')]),
        ),
    ]
