# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170820_0722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([]),
        ),
    ]
