# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0005_remove_sublist_session'),
        ('main', '0005_auto_20170801_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sublist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sublist.Sublist'),
            preserve_default=False,
        ),
    ]
