# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 00:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170820_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonUserPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('create_team', 'Can create a team'),)},
        ),
        migrations.AddField(
            model_name='nonuserplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
