# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:43
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_session_sublist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='sublist',
        ),
        migrations.AddField(
            model_name='division',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='a', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='a', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Division'),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
            preserve_default=False,
        ),
    ]
