# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170815_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
