# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170807_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ManyToManyField(to='main.Location'),
        ),
    ]
