# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170815_0354'),
        ('main', '0007_auto_20170818_2019'),
    ]

    operations = [
    ]
