# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170821_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=main.models.thumbnail_path),
        ),
    ]
