# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170807_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='location',
            new_name='locations',
        ),
    ]
