# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='main.CustomUser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='main.CustomUser'),
        ),
    ]
