# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170807_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Session'),
            preserve_default=False,
        ),
    ]
