# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teaminvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvite',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='teaminvite',
            name='responded',
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
