# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170807_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='subs',
        ),
        migrations.AddField(
            model_name='location',
            name='subs',
            field=models.ManyToManyField(blank=True, to='main.Sub'),
        ),
    ]
