# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170912_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
