# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sessionevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionevent',
            name='end_time',
        ),
    ]
