# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='sub date')),
                ('session_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.SessionEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together=set([('user', 'session_event')]),
        ),
    ]
