# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180113_1952'),
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together=set([('user', 'session_event')]),
        ),
    ]
