# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_auto_20180115_0159'),
        ('substitutes', '0003_initialize_permissions'),
    ]

    operations = [
    ]
